# This is a basic workflow to help you get started with Actions

name: Build Firmware

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    paths:
      - 'microfw/**'
      - '.github/workflows/build_sam3u_fw.yaml'

  pull_request:
    paths:
      - 'microfw/**'
      - '.github/workflows/build_sam3u_fw.yaml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fwbuild:
    # The type of runner that the job will run on
    name: Build all firmware to make sure compilation works
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install compilers
        run: >- 
          sudo apt install -y make build-essential gcc-arm-none-eabi
      - name: Build firmware
        run: >-
          cd microfw/CW310/src && make -j